'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';

type RecordValue = string | number | boolean | null | undefined;
type DataRecord = Record<string, RecordValue> & { id: string; active: boolean };
type Field = { key:string; label:string; type?:'text'|'email'|'number'|'checkbox'|'select'|'textarea'; required?:boolean; options?:{value:string;label:string}[]; readOnly?:boolean; step?:string };
type Column = { key:string; label:string; render?:(row:DataRecord)=>string };
type Props = { title:string;description:string;endpoint:string;singular:string;columns:Column[];fields:Field[];initial:Record<string,RecordValue>;searchPlaceholder:string;onLoadFields?:(signal:AbortSignal)=>Promise<Partial<Record<string,{value:string;label:string}[]>>> };

export function MasterDataCrud(props:Props) {
  const [items,setItems]=useState<DataRecord[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [search,setSearch]=useState(''),[active,setActive]=useState('true'),[open,setOpen]=useState(false),[editing,setEditing]=useState<DataRecord|null>(null);
  const [form,setForm]=useState<Record<string,RecordValue>>(props.initial),[fieldErrors,setFieldErrors]=useState<Record<string,string>>({}),[saving,setSaving]=useState(false),[dynamicOptions,setDynamicOptions]=useState<Partial<Record<string,{value:string;label:string}[]>>>({});
  const load=useCallback(async()=>{setLoading(true);setError('');try{const params=new URLSearchParams({search});if(active!=='all')params.set('active',active);const response=await fetch(`/api${props.endpoint}?${params}`,{credentials:'include'});if(!response.ok)throw new Error('Data could not be loaded');const data=await response.json() as {items:DataRecord[];total:number};setItems(data.items);setTotal(data.total)}catch(e){setError(e instanceof Error?e.message:'Data could not be loaded')}finally{setLoading(false)}},[active,props.endpoint,search]);
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]);
  useEffect(()=>{if(!props.onLoadFields)return;const controller=new AbortController();props.onLoadFields(controller.signal).then(setDynamicOptions).catch(()=>{});return()=>controller.abort()},[props]);
  function begin(row?:DataRecord){setEditing(row??null);setFieldErrors({});setForm(row?Object.fromEntries(Object.keys(props.initial).map(key=>[key,row[key]??props.initial[key]])):props.initial);setOpen(true)}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setFieldErrors({});try{const response=await fetch(`/api${props.endpoint}${editing?`/${editing.id}`:''}`,{method:editing?'PUT':'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(!response.ok){const body=await response.json() as {message?:string;fields?:Record<string,string>};setFieldErrors(body.fields??{_form:body.message??'Data could not be saved'});return}setOpen(false);await load()}finally{setSaving(false)}}
  const modalSize = props.fields.length > 4 ? 'crud-modal--wide' : 'crud-modal--compact';
  return <section className="module-index">
    <div className="page-title-row"><div><h1>{props.title}</h1><p className="muted">{props.description}</p></div><button className="primary-button" onClick={()=>begin()}>New {props.singular}</button></div>
    <div className="table-toolbar"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} aria-label={`Search ${props.title}`} placeholder={props.searchPlaceholder}/><div className="toolbar-actions"><select aria-label="Status filter" value={active} onChange={e=>setActive(e.target.value)}><option value="true">Active</option><option value="false">Inactive</option><option value="all">All status</option></select><span>{total} records</span></div></div>
    <div className="table-frame"><table><thead><tr>{props.columns.map(c=><th key={c.key}>{c.label}</th>)}<th className="table-column-actions">Action</th></tr></thead><tbody>{loading?<tr><td className="table-row-empty" colSpan={props.columns.length+1}><div className="table-empty">Loading...</div></td></tr>:error?<tr><td className="table-row-empty" colSpan={props.columns.length+1}><div className="table-empty"><strong>Could not load data</strong><span>{error}</span></div></td></tr>:items.length===0?<tr><td className="table-row-empty" colSpan={props.columns.length+1}><div className="table-empty"><strong>No data yet</strong><span>Click New {props.singular} to get started.</span></div></td></tr>:items.map(row=><tr key={row.id}>{props.columns.map(c=><td key={c.key}>{c.render?c.render(row):String(row[c.key]??'-')}</td>)}<td><button className="table-action" onClick={()=>begin(row)}>Edit</button></td></tr>)}</tbody></table></div>
    {open&&<><button className="crud-scrim" aria-label="Close form" onClick={()=>setOpen(false)}/><div className={`crud-modal ${modalSize}`} role="dialog" aria-modal="true" aria-label={`${editing?'Edit':'New'} ${props.singular}`}><div className="crud-modal-heading"><div><strong>{editing?'Edit':'New'} {props.singular}</strong><span>Enter the required information below.</span></div><button aria-label="Close form" onClick={()=>setOpen(false)}>×</button></div><form onSubmit={submit}>{fieldErrors._form&&<p className="form-error">{fieldErrors._form}</p>}<div className="crud-fields">{props.fields.map(field=><label key={field.key} className={field.type==='checkbox'?'check-field':''}><span>{field.label}{field.required?' *':''}</span>{field.type==='select'?<select value={String(form[field.key]??'')} onChange={e=>setForm(v=>({...v,[field.key]:e.target.value}))} required={field.required}><option value="">Select...</option>{(field.options??dynamicOptions[field.key]??[]).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:field.type==='checkbox'?<input type="checkbox" checked={Boolean(form[field.key])} onChange={e=>setForm(v=>({...v,[field.key]:e.target.checked}))}/>:field.type==='textarea'?<textarea value={String(form[field.key]??'')} onChange={e=>setForm(v=>({...v,[field.key]:e.target.value}))}/>:<input type={field.type??'text'} step={field.step} readOnly={field.readOnly} required={field.required} value={String(form[field.key]??'')} onChange={e=>setForm(v=>({...v,[field.key]:field.type==='number'?Number(e.target.value):e.target.value}))}/>} {fieldErrors[field.key]&&<small>{fieldErrors[field.key]}</small>}</label>)}</div><div className="crud-actions"><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-button" disabled={saving}>{saving?'Saving...':'Save'}</button></div></form></div></>}
  </section>
}
