BEGIN;
CREATE TABLE sales_orders (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),sales_order_number text NOT NULL,customer_id uuid NOT NULL,order_date date NOT NULL DEFAULT current_date,delivery_date date,customer_po_reference text NOT NULL DEFAULT '',notes text NOT NULL DEFAULT '',status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','SUBMITTED')),created_by_user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_by_user_id uuid NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),UNIQUE(tenant_id,sales_order_number),FOREIGN KEY(tenant_id,customer_id) REFERENCES customers(tenant_id,id),FOREIGN KEY(tenant_id,created_by_user_id) REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,updated_by_user_id) REFERENCES users(tenant_id,id)
);
CREATE TABLE sales_order_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),sales_order_id uuid NOT NULL,finished_good_id uuid NOT NULL,item_code_snapshot text NOT NULL,item_name_snapshot text NOT NULL,base_unit_snapshot text NOT NULL,quantity numeric(20,6) NOT NULL CHECK(quantity>0),sales_price_snapshot numeric(20,6) NOT NULL CHECK(sales_price_snapshot>0),currency_snapshot text NOT NULL,price_version integer NOT NULL,calculation_snapshot jsonb,sort_position integer NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,sales_order_id,finished_good_id),FOREIGN KEY(tenant_id,sales_order_id) REFERENCES sales_orders(tenant_id,id) ON DELETE CASCADE,FOREIGN KEY(tenant_id,finished_good_id) REFERENCES finished_goods(tenant_id,id));
ALTER TABLE sales_orders ENABLE ROW LEVEL SECURITY;ALTER TABLE sales_orders FORCE ROW LEVEL SECURITY;CREATE POLICY sales_orders_isolation ON sales_orders USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
ALTER TABLE sales_order_lines ENABLE ROW LEVEL SECURITY;ALTER TABLE sales_order_lines FORCE ROW LEVEL SECURITY;CREATE POLICY sales_order_lines_isolation ON sales_order_lines USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
GRANT SELECT,INSERT,UPDATE ON sales_orders,sales_order_lines TO nextgen_app;
INSERT INTO permissions(code,description) VALUES('sales_order.view','View sales orders'),('sales_order.create','Create sales orders'),('sales_order.edit_draft','Edit draft sales orders'),('sales_order.submit','Submit sales orders'),('sales_order.price.view','View sales prices') ON CONFLICT(code) DO UPDATE SET description=EXCLUDED.description;
INSERT INTO role_permissions(tenant_id,role_id,permission_code) SELECT r.tenant_id,r.id,p.code FROM roles r CROSS JOIN permissions p WHERE r.code='ADMIN' AND p.code IN('sales_order.view','sales_order.create','sales_order.edit_draft','sales_order.submit','sales_order.price.view') ON CONFLICT DO NOTHING;
CREATE TRIGGER activity_audit AFTER INSERT OR UPDATE OR DELETE ON sales_orders FOR EACH ROW EXECUTE FUNCTION record_activity_change();
COMMIT;
