BEGIN;
CREATE TABLE customer_deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),delivery_number text NOT NULL,sales_order_id uuid NOT NULL,delivery_date date NOT NULL DEFAULT current_date,notes text NOT NULL DEFAULT '',created_by_user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),UNIQUE(tenant_id,delivery_number),FOREIGN KEY(tenant_id,sales_order_id) REFERENCES sales_orders(tenant_id,id),FOREIGN KEY(tenant_id,created_by_user_id) REFERENCES users(tenant_id,id));
CREATE TABLE customer_delivery_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id),customer_delivery_id uuid NOT NULL,sales_order_line_id uuid NOT NULL,quantity numeric(20,6) NOT NULL CHECK(quantity>0),UNIQUE(tenant_id,id),UNIQUE(tenant_id,customer_delivery_id,sales_order_line_id),FOREIGN KEY(tenant_id,customer_delivery_id) REFERENCES customer_deliveries(tenant_id,id) ON DELETE CASCADE,FOREIGN KEY(tenant_id,sales_order_line_id) REFERENCES sales_order_lines(tenant_id,id));
ALTER TABLE customer_deliveries ENABLE ROW LEVEL SECURITY; ALTER TABLE customer_deliveries FORCE ROW LEVEL SECURITY; CREATE POLICY customer_deliveries_isolation ON customer_deliveries USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
ALTER TABLE customer_delivery_lines ENABLE ROW LEVEL SECURITY; ALTER TABLE customer_delivery_lines FORCE ROW LEVEL SECURITY; CREATE POLICY customer_delivery_lines_isolation ON customer_delivery_lines USING(tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id',true)::uuid);
GRANT SELECT,INSERT ON customer_deliveries,customer_delivery_lines TO nextgen_app;
INSERT INTO permissions(code,description) VALUES('customer_delivery.view','View customer deliveries'),('customer_delivery.create','Create customer deliveries') ON CONFLICT(code) DO UPDATE SET description=EXCLUDED.description;
INSERT INTO role_permissions(tenant_id,role_id,permission_code) SELECT r.tenant_id,r.id,p.code FROM roles r CROSS JOIN permissions p WHERE r.code='ADMIN' AND p.code IN('customer_delivery.view','customer_delivery.create') ON CONFLICT DO NOTHING;
COMMIT;
