export const deck = {
  title: 'Deta MRP',
  subtitle: 'A Smarter, Paperless Purchase Order Process',
  slides: [
    { id:'cover', kind:'cover', title:'Deta MRP', headline:'A Smarter, Paperless\nPurchase Order Process', body:'Simplify approvals. Improve visibility. Keep operations moving.' },
    { id:'challenge', kind:'challenge', title:'The Current Challenge', headline:'Purchase order approval should not stop when decision-makers are away.', bullets:['Paper documents require physical handovers.','Business travel can delay approval.','Teams have limited visibility into PO status.','Manual follow-ups take time and are difficult to track.'] },
    { id:'needs', kind:'needs', title:'What Businesses Need', headline:'A faster process, without losing control.', bullets:['Create and review purchase orders digitally.','Approve from anywhere.','Track every PO from submission to completion.','Keep documents and approval history in one place.','Give each team access based on their role.'] },
    { id:'product', kind:'product', title:'Introducing Deta MRP', headline:'One connected workspace for procurement and material control.', body:'Deta MRP is a ready-to-use platform that digitalizes purchase orders, approvals, receiving, inventory monitoring, and reporting.|The system can be customized to match each company’s workflow, roles, and operational requirements.' },
    { id:'process', kind:'process', title:'How It Works', headline:'From purchase request to stock visibility.', steps:['Create PO','Submit','Approve','Documents','Receive','Inventory','Report'], body:'Each step is connected, traceable, and accessible from one platform.' },
    { id:'approval', kind:'approval', title:'Paperless Approval', headline:'Approve wherever business takes you.', bullets:['Review PO details online.','Approve or reject without handling paper documents.','Receive email notifications for pending approvals.','Monitor approval status in real time.','Maintain a complete activity and decision history.'] },
    { id:'modules', kind:'modules', title:'Available Modules', headline:'Everything needed to keep the process connected.', modules:['Dashboard','Master Data','Supplier Orders','Online Approval','Delivery Documents','Material Receiving','Stock Inventory','Outgoing Materials','Reports','Users & Permissions','Email & Activity Logs'] },
    { id:'benefits', kind:'benefits', title:'Business Benefits', headline:'Less waiting. Better control. Clearer decisions.', benefits:[['Faster','Shorter PO approval cycle'],['Paperless','Reduced paper and manual handovers'],['Visible','Better visibility across teams'],['Accurate','Reliable receiving and inventory records'],['Accountable','Clear ownership and traceable activities'],['Consistent','A process that is easier to manage']] },
    { id:'customization', kind:'customization', title:'Built to Fit Your Process', headline:'Ready today. Customizable for tomorrow.', steps:[['Discover','Understand the current workflow and priorities.'],['Configure','Set up users, roles, master data, and approval rules.'],['Customize','Adjust forms, documents, and workflows where needed.'],['Validate','Test the process together with key users.'],['Launch','Train users and support the go-live.']] },
    { id:'timeline', kind:'timeline', title:'Estimated Timeline', headline:'A focused path to implementation.', stages:[['Process Discovery','1 week'],['Configuration & Customization','2–3 weeks'],['User Testing & Refinement','1 week'],['Training & Go-Live Preparation','1 week'],['Go-Live Support','1 week']], total:'Estimated total: 6–7 weeks', note:'The final timeline will be adjusted based on customization scope and user readiness.' },
    { id:'demo', kind:'demo', title:'See Deta MRP in Action', headline:'Let’s walk through the process.', steps:['Create a supplier order.','Submit it for online approval.','Review and approve the PO.','Generate the required documents.','Receive materials using Kanban scanning.','Monitor inventory and transaction history.'], body:'Next step: Align Deta MRP with your current process and identify the required customizations.' }
  ]
};
