import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { beforeEach, expect, it, vi } from 'vitest';
import { OrderIndex, OrderForm, OrderDetail } from './order-pages';
const { push, auth } = vi.hoisted(() => ({ push: vi.fn(), auth: { permissions: ['production.order', 'production.entry', 'production.report'] } }));
vi.mock('next/navigation', () => ({ useRouter: () => ({ push }) }));
vi.mock('../app-shell/app-shell', () => ({ useCurrentUser: () => auth }));
const order = { id:'o1',orderNumber:'PO-001',planNumber:'PL-001',partNumber:'FG-01',partName:'Panel',plantName:'Main',unitCode:'PCS',status:'RELEASED',plannedQty:'10',actualGood:'0',rejectQty:'0',wipQty:'0',entryCount:0,operations:[],materials:[],history:[],currency:'IDR',materialEstimate:'100',processEstimate:'20',materialCost:'0',processCost:'0',dueDate:'2026-09-30',periodStart:'2026-09-01' };
beforeEach(() => { vi.clearAllMocks(); auth.permissions=['production.order','production.entry','production.report']; });
function respond(value: unknown) { return { ok:true,json:async()=>value }; }
it('lists orders and hides create from viewers', async()=>{ auth.permissions=[]; vi.stubGlobal('fetch',vi.fn().mockResolvedValue(respond({items:[order]})));render(<OrderIndex/>);expect(await screen.findByText('PO-001')).toBeInTheDocument();expect(screen.queryByText('New Production Order')).not.toBeInTheDocument(); });
it('creates an order from an available approved planning line',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(respond({lines:[{id:'line1',planId:'plan1',planNumber:'PL-001',partNumber:'FG-01',partName:'Panel',remainingQty:'10',periodEnd:'2026-09-30',periodStart:'2026-09-01',unitCode:'PCS',plantName:'Main'}]})).mockResolvedValueOnce(respond({id:'saved'}));vi.stubGlobal('fetch',fetcher);render(<OrderForm planId="plan1"/>);await screen.findByText(/Available: 10/);fireEvent.change(screen.getByLabelText('Planned quantity'),{target:{value:'5'}});fireEvent.click(screen.getByRole('button',{name:'Release Production Order'}));await waitFor(()=>expect(push).toHaveBeenCalledWith('/production-orders/saved'));expect(JSON.parse(fetcher.mock.calls[1][1].body)).toMatchObject({planLineId:'line1',plannedQty:'5',dueDate:'2026-09-30'});});
it('rejects quantities beyond the available planning balance',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(respond({lines:[{id:'l',planId:'p',planNumber:'PL',partNumber:'FG',remainingQty:'10',periodEnd:'2026-09-30'}]})));render(<OrderForm planId="p"/>);await screen.findByText(/Available: 10/);fireEvent.change(screen.getByLabelText('Planned quantity'),{target:{value:'11'}});fireEvent.submit(screen.getByRole('button',{name:'Release Production Order'}).closest('form')!);expect(await screen.findByRole('alert')).toHaveTextContent('available planning balance');});
it('suppresses edit and cancel when an order has WIP',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(respond({...order,wipQty:'3',entryCount:1,status:'IN_PROGRESS'})));render(<OrderDetail id="o1"/>);await screen.findByText('PO-001');expect(screen.queryByRole('link',{name:'Edit order'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Cancel order'})).not.toBeInTheDocument();expect(screen.getByRole('link',{name:'New Daily Entry'})).toHaveAttribute('href','/daily-production/new?orderId=o1');});
